import = ["/home/pmoieni/.config/alacritty/rose-pine.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[shell]
args = ["-l"]
program = "fish"

[window]
opacity = 0.8
